import type { AIModelConfig, AIModelType, MusicGenre } from './types';

export const AI_MODELS: Record<AIModelType, AIModelConfig> = {
  'stable-audio-open': {
    id: 'stable-audio-open',
    name: 'Stable Audio Open',
    description:
      'Stability AI\'s open source 44.1kHz stereo model optimized for high fidelity music generation.',
    provider: 'huggingface',
    modelId: 'stabilityai/stable-audio-open-1.0',
    maxDuration: 95,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'ambient', 'rock', 'hip-hop', 'pop', 'dance', 'experimental'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'musicgen-large': {
    id: 'musicgen-large',
    name: 'Meta AudioCraft MusicGen Large',
    description:
      'Meta\'s flagship open MusicGen Large model for extended compositions with genre flexibility.',
    provider: 'huggingface',
    modelId: 'meta-llama/MusicGen-Large',
    maxDuration: 120,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'rock', 'jazz', 'classical', 'hip-hop', 'pop', 'experimental'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'musicgen-medium': {
    id: 'musicgen-medium',
    name: 'MusicGen Medium (HuggingFace Spaces)',
    description:
      'Optimized MusicGen medium distilled model for fast local/browser inference via ONNX.',
    provider: 'local',
    modelId: 'facebook/musicgen-medium',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'rock', 'jazz', 'classical', 'hip-hop', 'pop', 'experimental'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  riffusion: {
    id: 'riffusion',
    name: 'Riffusion',
    description:
      'Spectrogram-diffusion model for creative loops and experimental textures from text prompts.',
    provider: 'huggingface',
    modelId: 'riffusion/riffusion-model-v1',
    maxDuration: 30,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'experimental', 'ambient'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  audioldm2: {
    id: 'audioldm2',
    name: 'AudioLDM 2',
    description:
      'High fidelity text-to-audio model supporting detailed prompts and clean renderings.',
    provider: 'huggingface',
    modelId: 'haoheliu/audioldm2-large',
    maxDuration: 60,
    sampleRate: 48000,
    channels: 2,
    supportedGenres: ['ambient', 'experimental', 'electronic', 'hip-hop', 'pop'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'dance-diffusion': {
    id: 'dance-diffusion',
    name: 'Dance Diffusion',
    description:
      'Harmonai\'s dance/electronic focused diffusion model for beats and energetic tracks.',
    provider: 'huggingface',
    modelId: 'harmonai/dance-diffusion-vit-tiny',
    maxDuration: 45,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['dance', 'electronic', 'experimental'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  bark: {
    id: 'bark',
    name: 'Bark',
    description:
      'Suno\'s Bark model for multi-speaker audio generation, vocals, and soundscapes.',
    provider: 'huggingface',
    modelId: 'suno/bark',
    maxDuration: 45,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'experimental', 'pop', 'hip-hop'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  procedural: {
    id: 'procedural',
    name: 'Procedural (No API Key)',
    description:
      'Local algorithmic generator. Creates layered drum, bass and melody loops fully offline (tokenless fallback).',
    provider: 'local',
    modelId: 'procedural/local',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'dance', 'ambient', 'experimental', 'hip-hop', 'pop', 'custom'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  'tonejs-procedural': {
    id: 'tonejs-procedural',
    name: 'Tone.js - Procedural Loops',
    description:
      'Interactive music framework generating synths, sequences, and layered loops procedurally. Browser-native Web Audio API.',
    provider: 'local',
    modelId: 'tonejs-procedural',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'dance', 'ambient', 'experimental', 'pop', 'custom'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  'tonejs-synth': {
    id: 'tonejs-synth',
    name: 'Tone.js - PolySynth',
    description:
      'Dynamic polyphonic synthesis with envelope control and effects chains. Full synth capabilities in browser.',
    provider: 'local',
    modelId: 'tonejs-synth',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'ambient', 'experimental', 'custom'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  'scribbletune': {
    id: 'scribbletune',
    name: 'ScribbleTune - MIDI Sequencer',
    description:
      'Declarative JS library for procedural MIDI sequences (scales, chords, rhythms). Lightweight and customizable.',
    provider: 'local',
    modelId: 'scribbletune',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'dance', 'jazz', 'classical', 'custom'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  'abundant-music': {
    id: 'abundant-music',
    name: 'Abundant Music - One-Click Generator',
    description:
      'One-button procedural track generation with randomized rhythms, melodies, and harmonies. Instant results.',
    provider: 'local',
    modelId: 'abundant-music',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'pop', 'dance', 'experimental', 'custom'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  'procjam': {
    id: 'procjam',
    name: 'ProcJam - Phrase Engine',
    description:
      'GPL-licensed procedural phrase engine for beats and ambient layers. Complex rule-based generation.',
    provider: 'local',
    modelId: 'procjam',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'ambient', 'experimental', 'dance', 'custom'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  'magenta-melody': {
    id: 'magenta-melody',
    name: 'Magenta.js - Melody RNN',
    description:
      'Google TensorFlow.js ML model for melody generation from seed notes. Learns music patterns.',
    provider: 'local',
    modelId: 'magenta-melody',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'classical', 'jazz', 'pop', 'custom'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'magenta-music': {
    id: 'magenta-music',
    name: 'Magenta.js - MusicRNN',
    description:
      'Advanced TensorFlow.js composition model with longer sequences and style variations. Professional AI generation.',
    provider: 'local',
    modelId: 'magenta-music',
    maxDuration: 120,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'classical', 'jazz', 'pop', 'experimental', 'custom'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'magenta-music-rnn': {
    id: 'magenta-music-rnn',
    name: 'Magenta.js - Music RNN Continuous',
    description:
      'Continuous music generation with real-time style control. Generate infinite variations seamlessly.',
    provider: 'local',
    modelId: 'magenta-music-rnn',
    maxDuration: 120,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'experimental', 'pop', 'custom'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'markov-chains': {
    id: 'markov-chains',
    name: 'Markov Chain Sequencer',
    description:
      'Probabilistic note selection based on weighted transitions. Intelligent musical sequencing.',
    provider: 'local',
    modelId: 'markov-chains',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['jazz', 'ambient', 'classical', 'experimental', 'custom'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  'algorithmic-composition': {
    id: 'algorithmic-composition',
    name: 'Algorithmic Composition',
    description:
      'Advanced procedural generation combining L-Systems, chaos theory, and fractals. Complex and unique.',
    provider: 'local',
    modelId: 'algorithmic-composition',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['experimental', 'ambient', 'electronic', 'custom'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
};

export const GENRE_ROUTING: Record<MusicGenre, AIModelType[]> = {
  electronic: [
    'stable-audio-open',
    'dance-diffusion',
    'riffusion',
    'tonejs-procedural',
    'scribbletune',
    'procjam',
  ],
  dance: [
    'dance-diffusion',
    'stable-audio-open',
    'tonejs-procedural',
    'scribbletune',
    'procjam',
  ],
  ambient: [
    'musicgen-large',
    'audioldm2',
    'stable-audio-open',
    'tonejs-synth',
    'magenta-melody',
    'magenta-music',
    'algorithmic-composition',
  ],
  rock: [
    'musicgen-large',
    'stable-audio-open',
    'tonejs-procedural',
    'scribbletune',
  ],
  jazz: [
    'musicgen-large',
    'markov-chains',
    'scribbletune',
    'magenta-melody',
  ],
  classical: [
    'musicgen-large',
    'markov-chains',
    'magenta-music',
    'scribbletune',
    'algorithmic-composition',
  ],
  'hip-hop': [
    'stable-audio-open',
    'musicgen-large',
    'tonejs-procedural',
    'procjam',
    'scribbletune',
  ],
  pop: [
    'stable-audio-open',
    'musicgen-large',
    'tonejs-synth',
    'abundant-music',
    'magenta-melody',
  ],
  experimental: [
    'riffusion',
    'audioldm2',
    'bark',
    'algorithmic-composition',
    'magenta-music-rnn',
  ],
  custom: [
    'stable-audio-open',
    'musicgen-large',
    'musicgen-medium',
    'audioldm2',
    'riffusion',
    'dance-diffusion',
    'bark',
    'procedural',
    'tonejs-procedural',
    'tonejs-synth',
    'scribbletune',
    'abundant-music',
    'procjam',
    'magenta-melody',
    'magenta-music',
    'magenta-music-rnn',
    'markov-chains',
    'algorithmic-composition',
  ],
};
