import type { AIModelConfig, AIModelType, MusicGenre } from './types';

export const AI_MODELS: Record<AIModelType, AIModelConfig> = {
  'stable-audio-open': {
    id: 'stable-audio-open',
    name: 'Stable Audio Open',
    description:
      'Stability AI\'s open source 44.1kHz stereo model optimized for high fidelity music generation.',
    provider: 'huggingface',
    modelId: 'stabilityai/stable-audio-open-1.0',
    maxDuration: 95,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'ambient', 'rock', 'hip-hop', 'pop', 'dance', 'experimental'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'musicgen-large': {
    id: 'musicgen-large',
    name: 'Meta AudioCraft MusicGen Large',
    description:
      'Meta\'s flagship open MusicGen Large model for extended compositions with genre flexibility.',
    provider: 'huggingface',
    modelId: 'meta-llama/MusicGen-Large',
    maxDuration: 120,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'rock', 'jazz', 'classical', 'hip-hop', 'pop', 'experimental'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'musicgen-medium': {
    id: 'musicgen-medium',
    name: 'MusicGen Medium (HuggingFace Spaces)',
    description:
      'Optimized MusicGen medium distilled model for fast local/browser inference via ONNX.',
    provider: 'local',
    modelId: 'facebook/musicgen-medium',
    maxDuration: 60,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'rock', 'jazz', 'classical', 'hip-hop', 'pop', 'experimental'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  riffusion: {
    id: 'riffusion',
    name: 'Riffusion',
    description:
      'Spectrogram-diffusion model for creative loops and experimental textures from text prompts.',
    provider: 'huggingface',
    modelId: 'riffusion/riffusion-model-v1',
    maxDuration: 30,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['electronic', 'experimental', 'ambient'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  audioldm2: {
    id: 'audioldm2',
    name: 'AudioLDM 2',
    description:
      'High fidelity text-to-audio model supporting detailed prompts and clean renderings.',
    provider: 'huggingface',
    modelId: 'haoheliu/audioldm2-large',
    maxDuration: 60,
    sampleRate: 48000,
    channels: 2,
    supportedGenres: ['ambient', 'experimental', 'electronic', 'hip-hop', 'pop'],
    quality: 'high',
    free: true,
    requiresApiKey: false,
  },
  'dance-diffusion': {
    id: 'dance-diffusion',
    name: 'Dance Diffusion',
    description:
      'Harmonai\'s dance/electronic focused diffusion model for beats and energetic tracks.',
    provider: 'huggingface',
    modelId: 'harmonai/dance-diffusion-vit-tiny',
    maxDuration: 45,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['dance', 'electronic', 'experimental'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
  bark: {
    id: 'bark',
    name: 'Bark',
    description:
      'Suno\'s Bark model for multi-speaker audio generation, vocals, and soundscapes.',
    provider: 'huggingface',
    modelId: 'suno/bark',
    maxDuration: 45,
    sampleRate: 44100,
    channels: 2,
    supportedGenres: ['ambient', 'experimental', 'pop', 'hip-hop'],
    quality: 'medium',
    free: true,
    requiresApiKey: false,
  },
};

export const GENRE_ROUTING: Record<MusicGenre, AIModelType[]> = {
  electronic: ['stable-audio-open', 'dance-diffusion', 'riffusion'],
  dance: ['dance-diffusion', 'stable-audio-open'],
  ambient: ['musicgen-large', 'audioldm2', 'stable-audio-open'],
  rock: ['musicgen-large', 'stable-audio-open'],
  jazz: ['musicgen-large'],
  classical: ['musicgen-large'],
  'hip-hop': ['stable-audio-open', 'musicgen-large'],
  pop: ['stable-audio-open', 'musicgen-large'],
  experimental: ['riffusion', 'audioldm2', 'bark'],
  custom: [
    'stable-audio-open',
    'musicgen-large',
    'musicgen-medium',
    'audioldm2',
    'riffusion',
    'dance-diffusion',
    'bark',
  ],
};
